apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-feed-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twitter-feed
  template:
    metadata:
      labels:
        app: twitter-feed
    spec:
      containers:
      - name: twitter-feed
        image: iad.ocir.io/cloud_pursuit_west/twitterfeed:latest
        imagePullPolicy: Always
        ports:
        - name: twitter-feed
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-feed
  labels:
    app: twitter-feed
spec:
  ports:
  - port: 30000
    targetPort: 8080
  selector:
    app: twitter-feed
  type: ClusterIP
---
